# Generated by Django 4.2.4 on 2023-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_csv_file', models.FileField(blank=True, null=True, upload_to='datas/')),
            ],
        ),
    ]
